#!/usr/bin/env python

"""
Get the first N sequences in a fastq file.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fastq_first_n seqs.fastq 1000 > first.fastq
"""

###############################################################################
# The libraries we need #
import sys, os
from Bio import SeqIO
# Get the shell arguments #
if len(sys.argv) < 2: sys.exit(sys.modules[__name__].__doc__)
fa_path = sys.argv[1]
count = int(sys.argv[2])
# Check that the path is valid #
if not os.path.exists(fa_path): raise Exception("No file at %s." % fa_path)
# Function #
def get_count(gen, count):
    for x in xrange(count):
        yield gen.next()
# Do it #
seqs = SeqIO.parse(open(fa_path), 'fastq')
SeqIO.write(get_count(seqs, count), sys.stdout, "fastq")