#!/usr/bin/env python

"""
Randomly reorder sequences in a FASTQ

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this::
$ fastaq_mix < reads.fastq > reads_mixed.fastq
"""

# The libraries we need #
import sys
from random import shuffle
from Bio import SeqIO
# Do it #
all_seqs = SeqIO.parse(open(sys.stdin), 'fastq')
shuffle(all_seqs)
SeqIO.write(all_seqs, sys.stdout, 'fastq')