#!/usr/bin/env python

"""
Get specific sequences from a FASTQ file.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fastaq_to_db reads.fastq < list.txt > output.fastq
"""

# The libraries we need #
import sys, os
from Bio import SeqIO
# Get the shell arguments #
fq_path = sys.argv[1]
# Check that the path is valid #
if not os.path.exists(fq_path): raise Exception("No file at %s." % fq_path)
# Do it #
wanted = set(line.strip("\n") for line in sys.stdin)
records = (r for r in SeqIO.parse(fq_path, "fastq") if r.id in wanted)
count = SeqIO.write(records, sys.stdout, "fastq")
if count < len(wanted): sys.stderr.write("Warning: %i IDs not found in '%s'" % (len(wanted)-count, fq_path))