#!/usr/bin/env python

"""
Add a string to the front of every header.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fasta_prefix_headers reads.fasta --inplace
"""

# The libraries we need #
import sys, os, argparse, shutil, tempfile
from Bio import SeqIO
# Parse the shell arguments #
parser = argparse.ArgumentParser()
parser.description = sys.modules[__name__].__doc__
parser.formatter_class = argparse.RawDescriptionHelpFormatter
parser.add_argument("prefix", type=str)
parser.add_argument("path", type=str)
parser.add_argument("--inplace", action="store_true")
args = parser.parse_args()
# Check that the paths are valid #
if not os.path.exists(args.path): raise Exception("No file at %s." % args.path)
# Temp file #
if args.inplace:
    handle = tempfile.NamedTemporaryFile(delete=False)
    tmp_path = handle.name
else:
    handle = sys.stdout
# Change function #
def change(reads):
    for read in reads:
        read.id = args.prefix + read.id
        yield read
# Read and output #
reads = SeqIO.parse(args.path, 'fasta')
SeqIO.write(change(reads), handle, "fasta")
# Close #
handle.close()
# Move #
if args.inplace:
    os.remove(args.path)
    shutil.move(tmp_path, args.path)