#!/usr/bin/env python

"""
Simulate the exact effect of this UPARSE command:

	import sh
	sh.usearch7("--derep_fulllength", self.stdin, '-output', self.stdout, '-sizeout')

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fasta_make_unique < seqs.fasta > seqs_unique.fasta
"""

###############################################################################
# The libraries we need #
import sys, os
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from collection import Counter
# Function #
def make_unique(reads):
	counts = Counter()
	for read in reads: Counter.update([str(read.seq)])
	i = 0
	for read, count in counts.items():
		yield read = SeqRecord(Seq(read), name="sequence_" + str(i) + ";size=" + str(count) + ";")
		i += 1
# Do it #
reads = SeqIO.parse(sys.stdin, 'fasta')
SeqIO.write(make_unique(reads), sys.stdout, "fasta")
