#!/usr/bin/env python

"""
A custom made script to extract only the IDs from a fasta file.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fasta_list_ids < AMFJ01.fasta > ids.txt
"""

###############################################################################
# The libraries we need #
import sys
from Bio import SeqIO
# Do it #
ids = (r.id for r in SeqIO.parse(sys.stdin, 'fasta'))
sys.stdout.write('\n'.join(ids))