#!/usr/bin/env python

"""
A custom made script to remove the description from
FASTA files.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ ./fasta_remove_desc in.fasta > out.fasta
"""

###############################################################################
# Modules #
import sys
from Bio import SeqIO
# Match function #
def remove_desc(reads):
    for read in reads:
        read.description = ""
        yield read
# Read and output #
reads = SeqIO.parse(sys.stdin, 'fasta')
SeqIO.write(remove_desc(reads), sys.stdout, "fasta")