#!/usr/bin/env python

"""
Convert a non standard FASTA files to standard FASTA

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this::
$ fasta_rewrite reads.fasta reads_norm.fasta
"""

# The libraries we need #
import sys, os
from Bio import SeqIO
# Get the shell arguments #
fa_path = sys.argv[1]
out_path = sys.argv[2]
# Check that the path is valid #
if not os.path.exists(fa_path): raise Exception("No file at %s." % fa_path)
# Do it #
all_seqs = SeqIO.parse(open(fa_path), 'fasta')
with open(out_path, 'w') as handle: SeqIO.write(all_seqs, handle,'fasta')