#!/usr/bin/env python

"""
A custom made script to convert sequences in a
FASTA file from one alphabet to another.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ ./fasta_remove_desc < in.fasta > out.fasta
"""

###############################################################################
# Modules #
import sys
from Bio import SeqIO
# Match function #
def switch_alphabet(reads):
    for read in reads:
        read.seq = read.seq.transcribe()
        yield read
# Read and output #
reads = SeqIO.parse(sys.stdin, 'fasta')
SeqIO.write(switch_alphabet(reads), sys.stdout, "fasta")