#!/usr/bin/env python

"""
Simulate the exact effect of this UPARSE command:

	import sh
	sh.usearch7("--derep_fulllength", self.stdin, '-output', self.stdout, '-sizeout')

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fasta_make_unique seqs.fasta seqs_unique.fasta
"""

###############################################################################
# The libraries we need #
import sys
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from collections import Counter
# Get the shell arguments #
if len(sys.argv) < 2: sys.exit(sys.modules[__name__].__doc__)
input_path = sys.argv[1]
unique_path = sys.argv[2]
# Function #
def make_unique(reads):
	counts = Counter()
	for read in reads: counts.update([str(read.seq)])
	i = 0
	for read, count in counts.items():
		yield SeqRecord(Seq(read), id="sequence_" + str(i) + ";size=" + str(count) + ";", description="")
		i += 1
# Do it #
reads = SeqIO.parse(input_path, 'fasta')
SeqIO.write(make_unique(reads), unique_path, "fasta")