#!/usr/bin/env python

"""
Get sequences in a fasta file longer than a given size.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fasta_first_n seqs.fasta 1000 > first.fasta
"""

###############################################################################
# The libraries we need #
import sys, os
from Bio import SeqIO
# Get the shell arguments #
if len(sys.argv) < 2: sys.exit(sys.modules[__name__].__doc__)
fa_path = sys.argv[1]
count = int(sys.argv[2])
# Check that the path is valid #
if not os.path.exists(fa_path): raise Exception("No file at %s." % fa_path)
# Function #
def get_count(gen, count):
    for x in xrange(count):
        yield gen.next()
# Do it #
seqs = SeqIO.parse(open(fa_path), 'fasta')
SeqIO.write(get_count(seqs, count), sys.stdout, "fasta")