#!/usr/bin/env python

"""
A custom made script to count sequences in a fasta file.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ ./fasta_count genes.fasta
"""

###############################################################################
# Modules #
import sys, os
from Bio import SeqIO
# Check usage #
if len(sys.argv) != 2: sys.exit(sys.modules[__name__].__doc__)
# Get the shell arguments #
fasta_path = sys.argv[1]
# Check that the path is valid #
if not os.path.exists(fasta_path): raise Exception("No file at %s." % fasta_path)
# Read and output #
print sum([1 for x in SeqIO.parse(open(fasta_path), 'fasta')]), "sequences"