#!/usr/bin/env python

"""
Convert fasta alignemnts to relaxed phylip in O(N) memory
using the biopython library.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this::
$ fasta_to_phylip seqs.fasta seqs.phylip
"""

# The libraries we need #
import sys, os
from Bio import AlignIO
# Get the shell arguments #
fa_path = sys.argv[1]
ph_path = sys.argv[2]
# Check that the path is valid #
if not os.path.exists(fa_path): raise Exception("No file at %s." % fa_path)
# Do it #
with open(ph_path, "w") as handle:
    records = AlignIO.parse(open(fa_path), "fasta")
    count = AlignIO.write(records, handle, "phylip-relaxed")
