#!/usr/bin/env python

"""
Get the names and sizes of sequences in a FASTA file.

Written by Lucas Sinclair.
Kopimi.

You can use this script from the shell like this:
$ fasta_print_chromosomes seqs.fasta > contigs.chr
"""

###############################################################################
# The libraries we need #
import sys, os
from Bio import SeqIO
# Get the shell arguments #
fa_path = sys.argv[1]
# Check that the path is valid #
if not os.path.exists(fa_path): raise Exception("No file at %s." % fa_path)
# Do it #
seqs = ((s.id, str(len(s))) for s in SeqIO.parse(open(fa_path), 'fasta'))
# Print output #
for s in seqs: print '\t'.join(s)